### ISSUE TITLE
Bower integration with Spea/SpBowerBundle

### ISSUE THREAD

**Issue by lucasgranberg** [sonata-project/SonataCoreBundle#101]
I have my sonata bundles setup with Spea/SpBowerBundle and it works like a charm.

Is it something others might be interested in? Right now the bower integration is mentioned in the [master documentation of the adminBundle](http://sonata-project.org/bundles/admin/master/doc/reference/installation.html#enabling-sonataadminbundle-and-its-dependencies) but there is nothing in core.

Maybe sp bower could be one alternative as a suggest for the bundle and the "direct" way like in the admin documentation could be included in the core docs also. What do you think?

Right now I put the bower files inside the bundle but they could also go directly into the web/bundles/sonatacore or into app/Resources as a override somehow. I don't know whats the best practice there.

This is the conf I am using

``` yaml

sp_bower:
    bin: /usr/local/bin/bower
    assetic:
        nest_dependencies: false
    bundles:
        SonataAdminBundle:
            config_dir: .
            asset_dir: %kernel.root_dir%/../vendor/sonata-project/admin-bundle/Resources/public/vendor/
            cache: /Volumes/Drobo/Web/aktiva/presstanda/app/cache/bower
        SonataCoreBundle:
            config_dir: .
            asset_dir: %kernel.root_dir%/../vendor/sonata-project/core-bundle/Resources/public/vendor/
            cache: /Volumes/Drobo/Web/aktiva/presstanda/app/cache/bower
```
