### ISSUE TITLE
Issue in ResizeFormListener when persisting images with SonataMediaBundle

### ISSUE THREAD

**Issue by enekochan** [sonata-project/SonataCoreBundle#169]
I'm using SonataMediaBundle to store multiple images in an entity called `Restaurant`. I've also created a `RestaurantHasMedia` for the OneToMany relation and the related Admin classes. The issue happens when I add an image and the save the entity or I try to add a second image to the Restaurant entity from the SonataAdmin. This is what I get:

> Error: Cannot use object of type `AppBundle\Entity\RestaurantHasMedia` as array
> in vendor/sonata-project/core-bundle/Form/EventListener/ResizeFormListener.php at line 166   -
>                $form->add($name, $this->type, $options);
>            }
>            if (isset($value['_delete'])) {
>                $this->removed[] = $name;
>            }
>        }

Debugging it I've seen that `$value` comes as a `AppBundle\Entity\RestaurantHasMedia` object so I've fixed it adding an `is_array` check:

```php
            if (is_array($value) && isset($value['_delete'])) {
                $this->removed[] = $name;
            }
```

Now it works but I'm thinking that the problem may be in my code and not in SonataCoreBundle. Even though I wanted to share just in case I found a bug. After lots of days trying to have multiple images in an entity using SonataMediaBundle this has been the only "successful" code for me.

This is how my code more or less looks like (edited other entity properties for simplicity):

```php
/**
 * @ORM\Entity
 * @ORM\Table(name="restaurants")
 */
class Restaurant
{
    ...
    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\RestaurantHasMedia", mappedBy="restaurantMedias", cascade={"persist","remove"}, fetch="LAZY")
     */
    protected $images;
}
```

```php
/**
 * @ORM\Entity
 * @ORM\Table(name="restaurant_media")
 */
class RestaurantHasMedia
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var \Application\Sonata\MediaBundle\Entity\Media
     * @Assert\NotBlank()
     * @ORM\ManyToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media", cascade={"persist"}, fetch="LAZY")
     * @ORM\JoinColumn(name="media_id", referencedColumnName="id")
     */
    protected $media;

    /**
     * @var \AppBundle\Entity\Restaurant
     * @Assert\NotBlank()
     * @ORM\ManyToOne(targetEntity="\AppBundle\Entity\Restaurant", cascade={"persist","remove"}, inversedBy="images", fetch="LAZY")
     * @ORM\JoinColumn(name="restaurant_id", referencedColumnName="id", nullable=true)
     */
    protected $restaurantMedias;
    ...
}
```

And this are the Admin classes:

```php
class RestaurantAdmin extends Admin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $this->setTemplate('edit', 'SonataAdminBundle:CRUD:edit.html.twig');

        /** @var $restaurant \AppBundle\Entity\Restaurant */
        $restaurant = $this->getSubject();

        $formMapper
            ->with('Media')
                ->add(
                    'images',
                    'sonata_type_collection',
                    array(
                        'cascade_validation' => false,
                        'type_options' => array('delete' => false),
                    ),
                    array(
                        'edit' => 'inline',
                        'inline' => 'table',
                        'sortable' => 'position',
                        'link_parameters' => array('context' => 'default'),
                        'admin_code' => 'sonata.admin.restaurant_has_media',
                    )
                )
            ->end()
        ;
    }

    public function prePersist($restaurant)
    {
        $this->updateImages($restaurant);
    }

    public function preUpdate($restaurant)
    {
        $this->updateImages($restaurant);
    }

    private function updateImages(&$restaurant)
    {
        foreach ($restaurant->getImages() as $image) {
            $image->setRestaurantMedias($restaurant);
        }
    }
}
```

```php
class RestaurantHasMediaAdmin extends Admin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add(
            'media',
            'sonata_type_model_list',
            array(
                'required' => false
            ),
            array(
                'link_parameters' => array(
                    'context'  => 'restaurants',
                    'provider' => 'sonata.media.provider.image',
                ),
            )
        );
    }
}
```

services.yml:
```yml
    sonata.admin.restaurant:
        class: AppBundle\Admin\RestaurantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Restaurant" }
        arguments:
            - ~
            - AppBundle\Entity\Restaurant
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    sonata.admin.restaurant_has_media:
        class: AppBundle\Admin\RestaurantHasMediaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "RestaurantHasMedia" }
        arguments:
            - ~
            - AppBundle\Entity\RestaurantHasMedia
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
```
